trigger:
  branches:
    include:
    - master
stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: 11.x
      displayName: instalando node js
    - task: CmdLine@2
      displayName: clone from github to wiki
      inputs:
        script: "echo \"clonando sitio web\"\ngit clone https://github.com/alejandro3FX/mi-webpage.git web   \n\necho \"creando carpeta en un nivel más atrás\"\nmkdir ./../web   \necho \"moviendo sitio web\"\nmv web/* ./../web\necho \"creando carpetas estáticas\"     \nmkdir ./../web/content\necho \"copiando contenido\"   \nmv ./* ./../web/content\nmkdir web\necho \"ubicando toda la web mezclada en carpeta web\"\nmv ./../web/* ./web\n"
    - task: replacetokens@3
      inputs:
        rootDirectory: $(Build.SourcesDirectory)
        targetFiles: '**/config.js'
        encoding: auto
        writeBOM: true
        actionOnMissing: warn
        keepToken: false
        tokenPrefix: '#{'
        tokenSuffix: '}#'
        useLegacyPattern: false
        enableTelemetry: false
    - task: CmdLine@2
      displayName: instalando gatsby
      inputs:
        script: >
          npm install -g gatsby-cli
    - task: Bash@3
      inputs:
        targetType: inline
        script: npm install
        workingDirectory: $(Build.SourcesDirectory)/web
      displayName: npm install
    - task: Bash@3
      inputs:
        targetType: inline
        script: npm install --save-dev @babel/plugin-proposal-export-default-from
        workingDirectory: $(Build.SourcesDirectory)/web
      displayName: npm install babel
    - task: Bash@3
      inputs:
        targetType: inline
        script: gatsby build
        workingDirectory: $(Build.SourcesDirectory)/web
      displayName: gatsby build
    - task: CopyFiles@2
      inputs:
        SourceFolder: $(Build.SourcesDirectory)/web/public
        Contents: '**'
        TargetFolder: $(Build.ArtifactStagingDirectory)
        CleanTargetFolder: true
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: $(Build.ArtifactStagingDirectory)
        ArtifactName: drop
        publishLocation: container

